#ifndef SIMPLETCPCHATCLIENT_GLOBAL_H
#define SIMPLETCPCHATCLIENT_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SIMPLETCPCHATCLIENT_LIBRARY)
#define SIMPLETCPCHATCLIENT_EXPORT Q_DECL_EXPORT
#else
#define SIMPLETCPCHATCLIENT_EXPORT Q_DECL_IMPORT
#endif

#endif // SIMPLETCPCHATCLIENT_GLOBAL_H
